blog/urls.py
from django.conf.urls import url
from .import views

#声明该url对应的APP
app_name = 'blog'

#视图与路由进行绑定
urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$',views.detail,name='detail'),  #文章地址页
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),    #归档地址页
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),     #分类地址页
]

comments/urls.py
from django.conf.urls import url

from  . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name='post_comment'),
    ]

second_blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'',include('blog.urls')),
    url(r'',include('comments.urls')),
]

blog/models.py
# -*- coding:utf-8 -*-

from django.db import models    #必须继承模型类
from django.contrib.auth.models import User     #自带的User模块
from django.utils.six import python_2_unicode_compatible    #兼容PY2 和 PY3
from django.urls import reverse
import markdown
from django.utils.html import strip_tags

#文章类别Category
@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self): # __str__显示返回的内容
        return self.name

#文章的标签
@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

#文章的内容
@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    create_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200,blank=True)
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag,blank=True)
    author = models.ForeignKey(User)
    views = models.PositiveIntegerField(default=0) #统计阅读数量

    def __str__(self):
        return self.title

    #约定俗成的方法获取文章url
    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

    # 复写save方法
    # def save(self,*args,**kwargs):
    #     #如果没有填写再要
    #     if not self.excerpt:
    #         md = markdown.Markdown(extensions=[
    #             'markdown.extensions.extra',
    #             'markdown.extensions.codelilite'
    #         ])
    #         #先将Markdown 文本渲染成HTML文本
    #         #strip_tag 去掉全部HTML标签
    #         #从文本中摘取54个字符赋excerpt
    #         self.excerpt = strip_tags(md.convert(self.body))[:54]
    #
    #     super(Post,self).save(*args,**kwargs)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    #内部内 Meta方法显示
    class Meta:
        ordering = ['-create_time','title']

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible

@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Post,Category
from comments.forms import CommentForm
import markdown
from django.views.generic import ListView,DetailView  #通用视图类

#   博客首页方法普通方法
# def index(request):
#     post_list = Post.objects.all()
#     return render(request,'blog/index.html',context={'post_list':post_list})

#   博客首页方法二：通用视图类
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    #指定paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 2

    def get_context_data(self, **kwargs):

        #首先获取父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        #父类生成的字典中已有paginator、page_obj、is_paginated
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        #调用自己写的pagination_data方法，获得显示分页导航条需要的数据，见下方
        pagination_data = self.pagination_data(paginator,page,is_paginated)

        #将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典
        context.update(pagination_data)

        #将跟新后的 context 返回，以便 ListView 使用这个字典中模板变量去渲染
        #注意此时 context 字典中已有了显示分页导航条所需要的数据
        return  context

    def pagination_data(self,paginator,page,is_paginated):
        # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
        if not is_paginated:
            return {}

        #当前页左边连续的页码，初始值为空
        left = []

        #当前页左边连续的页码，初始值为空
        right = []

        #标识第1页页码后是否需要显示省略号
        left_has_more = False

        #标识最后一页页码前是否需要显示省略号
        right_has_more = False

        #标识是否需要显示第 1 页的页码号
        #因为如果当前页左边的连续页码中已经含有第1页的页码号，此时就无需在显示第1页的页码号
        #其他情况下第1页的页码是始终需要显示的
        #初始值为False
        first = False

        #标识是否需要显示最后一页的页码号
        #需要此指示变量的理由和上面的相同
        last = False

        #获取用户当前请求的页码号
        page_number = page.number

        #获取分页后的总页数
        total_pages = paginator.num_pages

        #获取整个分页页码列表
        page_range = paginator.page_range


  # 博客详情页：普通方法
def detail(request,pk):
    #   get_object_or_404有就获取，没有就报404
    post = get_object_or_404(Post,pk=pk)

    #阅读量+1
    post.increase_views()

    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    form = CommentForm()
    #   获取这篇 post 下全部评论
    comment_list = post.comment_set.all()

    #   将文章、表单、以及文章下的评论列表作为模板变量传递给 detail.html，以便渲染数据
    context = {'post':post,
               'form':form,
               'comment_list':comment_list
                }
    return render(request,'blog/detail.html',context=context)
# 博客详情页：通用视图类


#   博客归档一：普通方法
# def archives(request,year,month):
#     post_list = Post.objects.filter(create_time__year=year,
#                                     create_time__month=month
#                                     )
#     return render(request,'blog/index.html',context={'post_list':post_list})


#   博客归档二：通用视图类
class ArchivesView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year =self.kwargs.get('year')
        month =self.kwargs.get('month')
        return super(ArchivesView,self).get_queryset().filter(create_time__year=year,
                                                              create_time__month=month,
                                                              )
#   博客分类方法一：普通方法
# def category(request,pk):
#     cate = get_object_or_404(Category,pk=pk)
#     post_list = Post.objects.filter(category=cate)
#     return render(request,'blog/index.html',context={'post_list':post_list})

#   博客分类方法二：通用视图类
class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return super(CategoryView,self).get_queryset().filter(category=cate)

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">{{ post.title }}</h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">4 评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                {{ post.body |safe}}
            </div>
        </article>


{#<section class="comment-area" id="comment-area">#}

    <h3>发表评论</h3>
    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="{{ form.name.id_for_label}}">名字：</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.url.id_for_label }}">网址：</label>
                {{ form.url }}
                {{ form.url.errors }}
            </div>
            <div class="col-md-12">
                <label for="{{ form.text.id_for_label }}">评论：</label>
                {{ form.text }}
                {{ form.text.errors }}

                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div>    <!-- row -->
    </form>

    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="nickname">{{ comment.name }}</span>
                <time class="submit-date">{{ comment.created_time }}</time>
                <div class="text">
                   {{ comment.text |safe|linebreaksbr }}
                </div>
            </li>
            {% empty %}
                暂无评论！
            {% endfor %}
        </ul>
    </div>
{#</section>#}
{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">4 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{ post.body | truncatechars:54 }}</p>
            <div class="read-more cl-effect-14">
                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>

    {% empty %}
        <div class="no-post">暂时还未发表文章！</div>
    {% endfor %}

    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
{#    <div class="pagination">#}
{#        <ul>#}
{#            <li><a href="">1</a></li>#}
{#            <li><a href="">...</a></li>#}
{#            <li><a href="">4</a></li>#}
{#            <li><a href="">5</a></li>#}
{#            <li class="current"><a href="">6</a></li>#}
{#            <li><a href="">7</a></li>#}
{#            <li><a href="">8</a></li>#}
{#            <li><a href="">...</a></li>#}
{#            <li><a href="">11</a></li>#}
{#        </ul>#}
{#    </div>#}
{#    </article>#}
{% if is_paginated %}
    <div class="pagination-simple">
    <!-- 如果当前页还有上一页，显示一个上一页按钮 -->
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
     {% endif %}
    <!--显示当前页面信息-->
    <span class="current">第{{ page_obj.number }}页 / 共{{ paginator.num_pages }}页</span>
    <!--如果当前页面还有下一页，显示一个下一页按钮-->
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
    {% endif %}
    </div>
{% endif %}
{% endblock main %}